In [ ]:
matrix = {
    35: [0.5, 2.0, 3.5],
    38: [1.0, 2.5],
    42: [1.5, 3.0],
}

matrix.keys()

dict_keys([35, 38, 42])

In [3]:
matrix[35]

[0.5, 2.0, 3.5]

In [7]:
v = np.array([95.671, 95.871, 96.104, 96.486, 96.704, 96.946, 97.420, 97.612, 97.853, 98.275, 98.493])
import numpy as np
v = v - v[0]


In [8]:
v

array([0.   , 0.2  , 0.433, 0.815, 1.033, 1.275, 1.749, 1.941, 2.182,
       2.604, 2.822])

In [9]:
def scale_range(v, y):
    """
    Escala un vector manteniendo el primer elemento fijo, de manera que
    el último menos el primero pase a valer (x + y), donde x es el
    rango original.

    v: lista [v0, v1, ..., vn]
    y: incremento deseado del rango

    return: nueva lista escalada
    """
    if len(v) < 2:
        return v[:]  # no tiene rango

    v0 = v[0]
    x = v[-1] - v0  # rango original

    if x == 0:
        # No se puede escalar un rango cero, extender todos por y
        return [v0 + y for _ in v]

    factor = (x + y) / x

    return [v0 + (e - v0) * factor for e in v]


In [10]:
scale_range(v, 0.9)

[np.float64(0.0),
 np.float64(0.2637845499645494),
 np.float64(0.5710935506732723),
 np.float64(1.0749220411055969),
 np.float64(1.3624472005669581),
 np.float64(1.6816265060240867),
 np.float64(2.3067958894401093),
 np.float64(2.560029057406082),
 np.float64(2.877889440113382),
 np.float64(3.4344748405386274),
 np.float64(3.7219999999999884)]

In [15]:
import numpy as np

a =  np.array([0,    0.937, 1.875, 2.812])
ad = np.diff(a)

In [16]:
b = np.array([0.12, 0.90])

In [17]:
bd = np.diff(b)

In [18]:
ad

array([0.937, 0.938, 0.937])

In [19]:
bd

array([0.78])

In [23]:
bd = np.concatenate([bd, np.full(3-1,0)])

In [24]:
bd

array([0.78, 0.  , 0.  ])

In [26]:
cd = np.abs(ad - bd)

In [28]:
np.any(cd < 0.12)

np.False_

In [29]:
tolerance = 0.12
cd < tolerance

array([False, False, False])

In [30]:
melodie = np.array([10.949, 11.091, 11.235, 11.383, 11.522,11.670, 11.809, 11.954])

In [32]:
mnorm = melodie - melodie[0]

In [34]:
mnorm*1.243

array([0.      , 0.176506, 0.355498, 0.539462, 0.712239, 0.896203,
       1.06898 , 1.249215])